volkswagen_id_start_stop_charging:
  name: Volkswagen ID Start or Stop Charging
  description: Starts or stops charging of Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops charging.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"

volkswagen_id_set_climatisation:
  name: Volkswagen ID Set Climatisation
  description: Sets climatisation in Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    start_stop:
      name: Start or Stop
      description: Starts or stops climatisation.
      required: true
      selector:
        select:
          options:
            - "start"
            - "stop"
    target_temp:
      name: Target Temperature.
      description: Sets target temperature in celsius.
      required: false
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "ºC"

volkswagen_id_set_ac_charge_speed:
  name: Volkswagen ID Set AC Charge speed
  description: Sets the AC charging speed in Volkswagen ID cars.
  fields:
    vin:
      name: VIN
      description: Vehicle identification number for the car.
      required: true
      example: WVGZZZA1ZMP001337
      selector:
        text:
    maximum_reduced:
      name: Maximum or reduced
      description: Starts or stops climatisation.
      required: true
      selector:
        select:
          options:
            - "maximum"
            - "16A"
            - "13A"
            - "10A"
            - "5A"
